### ISSUE TITLE
Only one room available when configuring room colors

### ISSUE THREAD

**Issue by kevinduong** [sca075/valetudo_vacuum_camera#160]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

When changing room colors, only one option shows up for one room. The integration is reporting multiple segements (7). When adjusting this color, it didn't modify the floor color which I would have expected if there was an issue with segments/rooms. It correctly updated the color of the one room.  

![image](https://github.com/sca075/valetudo_vacuum_camera/assets/2790080/f0d94170-7157-42f4-bdf5-e9303bb13d93)

![image](https://github.com/sca075/valetudo_vacuum_camera/assets/2790080/c03c2cc4-3741-4c93-9e87-534d2be7c6de)

### What version of an integration has described problem?

2024.6.0

### What vacuum model do you have problems with?

Roborock S5 Valetudo

### Please firmware installed on your Vacuum.

2024.02.0

### What type of platform you use?

VEMLinux (Virtual Machine) such as Proxmox, VMWare, etc.

### What version of Home Assistant do you use?

core-2024.5.5

### What type of installation are you running?

Home Assistant OS

**Comment by sca075** [comment]
@kevinduong is there any errors in the logs of HA?
I used an S5 too to check it pre-release. It is possible that the rooms data was not available. Can you please share the logs?

**Comment by kevinduong** [comment]
I'm not seeing anything in my HA logs that could relate to this.

**Comment by sca075** [comment]
That file should come with the rooms colours rename functions.. this is why probably I didn't get it in tests I've done.. sorry for that, I will fix it as soon. Thanks a lot @kevinduong.

**Comment by kevinduong** [comment]
No worries. Glad I could help out in some way. Thanks for spending the time to look into it.

**Comment by jgkawell** [comment]
Just for the record I'm having the same issue with my (new) installation.

**Comment by sca075** [comment]
Well currently we have a bigger problem to solve..  #161  but I promise I will do my best to fix this, as per there will be to reinstall the camera probably with the fix of #161. It feels really sad honestly... I found anyhow a lot of small imperfections and 2024.06.0 was released too early.. I had no time to fully test it. I admit the next will be not that better but I will do my best to keep it working.. as per it was designed.

**Comment by jgkawell** [comment]
No worries, thanks for building this and trying to fix things! :) Until fixes come out could I just roll back to the last version? I'm assuming that won't break anything.

**Comment by sca075** [comment]
Did release the 2024.06.1 hopefully this issue will be closed too by then. The release is locked as requires HA 2024.6.0.
You can although test it if you want, downloading the main, please note that common.py currently in use on the camera 2024.06.0 or earlier is the one you should keep when you want to test it. I could prepare a test release if needed,
Please do not forget to start the project if you didn't yet.

**Comment by sca075** [comment]
@kevinduong and @jgkawell I suppose by now you are aware that unfortunately the issue with users_data.py is persisting, I got also a validation error for the calibration_data (one of the two vacuums I have is with battery empty and this is creating this error). 

Will review the code again as soon I'm done at work.

**Comment by sca075** [comment]
@kevinduong  just one question the problem with rooms colours was then solved?

**Comment by sca075** [comment]
@rj-d2 will change the default value and in the the next 2024.06.3b2 we can test if this works for you guys.

**Comment by sca075** [comment]
The issue was closed automatically because of the pull request merged few minutes ago. I will move it to discussions, please test the 2024.06.3b2 that will be published soon.
