### ISSUE TITLE
The camera crash  from Home Assistant 2024.06.0

### ISSUE THREAD

**Issue by sca075** [sca075/valetudo_vacuum_camera#161]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Testing the beta 1 of Home Assistant the camera will not load because of the new improvements in MQTT.
I will work on a solution as soon and try to release the version that will fix this huge issue. 

### What version of an integration has described problem?

2024.06.0

### What was the last working version of an integration?

none before.

### What vacuum model do you have problems with?

Roborock.S5

### Please firmware installed on your Vacuum.

2024.02.0

### What type of platform you use?

ARM (Raspberry Pi, Odroid, etc.) > 4GB

### What version of Home Assistant do you use?

2024.6.0b1

### What type of installation are you running?

Home Assistant OS

### Additional information

mmmmm :(

**Comment by sca075** [comment]
Long ago was introduced in this "integration" the configuration of the camera as part of the vacuum entity.

We currently have two possible solutions. 

1) Fully integrate the vacuum.. that in order words can be discovered as there's a discovery future in the vacuum.

2) revert the camera as an HA entity separate from the vacuums (not visible in MQTT). This would be a braking change for your configurations as the entity id will change.

As per the 2024.6.0 of HA will be published on next Monday.. would probably go for the number 2. Also because there was a kind agreement with the vacuums developers to do not integrate the vacuums with this custom component.

**Comment by jgkawell** [comment]
Yeah I think the second option makes a lot of sense. It's more explicit to have it as a separate entity anyway and though it means updating dashboards/automations it should avoid issues in the future.

**Comment by sca075** [comment]
@jgkawell there was probably an issue with the HassKey that replaced the get_mqtt_data on the new version of Home Assistant, I'm currently downloading the 2026.6.0b2 and we will see if it will be necessary to go for the solution two.
In any case in the begging the camera was design to be a stand alone. So probably if this patch that I will commit in few minutes (that include also some modification that should fix #160).. I will later consider to move ahed with this.

**Comment by sca075** [comment]
Solution tested on pull #162 will publish soon the fix for issue #161! :)

**Comment by sca075** [comment]
Confirmed also boot after installing the 2024.6.0b3, I think this 2024.06.1 will work at 100%.

**Comment by rohankapoorcom** [comment]
Home Assistant is designed so that multiple integrations can add entities to the same device so that they fit together in the UI in the system (and naming is automatically done). That's how I originally implemented this for this integration. I don't think it makes sense to revert that functionality and fixing it. Home Assistant does regularly change interfaces for internal integrations, making changes to support that is normal. If this was an internal integration (living directly in Home Assistant repo), it would have been fixed as part of the merge of that [change](https://developers.home-assistant.io/blog/2024/05/01/improved-hass-data-typing).

**Comment by sca075** [comment]
> Home Assistant is designed so that multiple integrations can add entities to the same device so that they fit together in the UI in the system (and naming is automatically done

Hopefully we will not need to change it.. as well there are changes on MQTT that we will need to study ;)
