### ISSUE TITLE
Forks Immediate Mandatory Update to be done!

### ISSUE THREAD

**Issue by sca075** [sca075/valetudo_vacuum_camera#181]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Dear Fork Owners,

@gunjambi, @kodbuzz, @rohankapoorcom, @tenfire and @tjorim

In light of [recent conversations](https://github.com/home-assistant/brands/pull/5533#issuecomment-2145907370) with @hypfer and the understandable concerns raised, we need to ensure all forks of this project are updated to the current main repository. Some forks still display the Valetudo logo and have not yet incorporated the recently added NOTICE.txt and README updates.

To prevent confusion and ensure compliance, I would kindly request that you update your forks as soon as possible. If updating is not feasible, we ask that you consider deleting your forks to avoid any potential issues.

Additionally, please note that the owners of the forks are not held responsible for any infractions if they comply with this update request.

Thank you for your understanding and cooperation.
 sca075

### What version of an integration has described problem?

all

### What was the last working version of an integration?

none

### What vacuum model do you have problems with?

not related.

### Please firmware installed on your Vacuum.

all

### What type of platform you use?

Intel NUC (or generic x86_64)

### What version of Home Assistant do you use?

all

### What type of installation are you running?

Home Assistant OS

**Comment by sca075** [comment]
@gunjambi  completed , thanks a lot for it.

**Comment by tenfire** [comment]
I have now deleted my fork

**Comment by sca075** [comment]
@tenfire  thank you for the feedback

**Comment by sca075** [comment]
thanks also @tjorim

**Comment by sca075** [comment]
@kodbuzz thanks a lot we can close now this issue and we are all in-line with this requirements, thanks a lot to you all guys.
