### ISSUE TITLE
camera entity does not show image and it seems it does not pick up the mqtt message when mqtt connection is used with user homeassistant

### ISSUE THREAD

**Issue by NODeeJay** [sca075/valetudo_vacuum_camera#21]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

I tried to get the valetudo map displayed in the Xiaomi add-on from Piotr. I followed the instructions and installed both add-ons. I configured the camera with my MQTT provider, but it seems not to create an image at all.

I enabled debug logging and see the addon connecting to MQTT and subscribe to the correct topic:
`2023-08-25 22:20:55.594 DEBUG (Thread-107 (_thread_main)) [custom_components.valetudo_vacuum_camera.valetudo.connector] Subscribed to MQTT broker with topic: valetudo/Robi`

but when the image comes:
![image](https://github.com/sca075/valetudo_vacuum_camera/assets/83764033/0ba9cadf-fdca-46e4-b205-ff7ebd18fee3)

```
2023-08-25 22:20:58.709 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on valetudo/Robi/MapData/map-data-hass (qos=0): b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x02\xd0\x00\x00\x01\xe0\x08\x02\x00\x00\x00\x03\xa7\xcd\xfb\x00\x00\\6IDATx\xda\xed\xbd\xd9o\x1dU\xda\xb7\xdd\xff@\x9fr\xc4\x11\x07}\xc0\x01\x07HHH-\xa4\x16R\x0b!\x84\x10\x1fM?

[...]

cc$)\xcf\x99\x06\x851\x1c\xae@7\xd9p9\xeb\x89\x08\xf2\xba\xf94J\xb0\xf0\xff\xbb.\xec\xecN9l\xc2\xee\x04\xf6z\x9d\xb87\xec\x15\xa5\xcd\xf4\xc1\x86\x08\xdf\xfc?\x9b"\xf4\xa0\xf8\xe9\xf2\x8d\xc4J\xf3/_c8\x8a\x88;\xad\xbemqs\xaa\x9dk\x1e\xbe\xd9\xe9\xdd\xdd\xadge~\xbb\\\x8f\x94\x9b\rY\xe5\x8c\xea!5\xb7\xd8\x17\xf17\xbf\xed\xd2a\xb5\xa6,\xd7=\rf\x9c\x83\xa6\x96\x07\t\x08\x7f\xa4\x19\xb9R~\xe3\xaew\xce\xfa\xfd\x1e\xbf\x1ds\x90>\x9b\xdbq\xd5p]]zr\xc0\x87\xd3=\xc2Htu\xeb\xb5\x0f\xbfl\xd4\xdf9o\x93^\xf0y\xadN\x0f\x8f\xba\x16R\x9a\xcb\x8f\xef\xdc\xd5W\x9f\xb4L-\xde\xaa\xeb63\x98\xbad\x88\xf9\xcd'

```

it does not seem to get further processed by the component, at least I am missing `_LOGGER.debug("Received " + self._mqtt_topic + " image data from MQTT")` which I found in the connector. Also the snapshot directory in the customer_component folder is empty.

In `custom:valetudo-map-card` the image works fine, which is also saved from the mqtt message.

Can I somehow increase the logging even more? Any idea how to troubleshoot that? Is it because it's an S5 Max? But shouldn't Valetudo provide the map in valetudo form/as PNG?

### What version of an integration has described problem?

1.3.4

### What vacuum model do you have problems with?

Roborock.S5Max

### Please firmware installed on your Vacuum.

2023.08.0

### What version of Home Assistant do you use?

2023.8.4

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
N/A
```

### Logs or Errors shown in the HA snapshots (please enable the Debug Mode)

```shell
see above
```

### Additional information

I noticed the component re-registers sporadically several times within a minute a couple of times quickly after each other (~5 - 20 seconds) I get `[custom_components.valetudo_vacuum_camera.valetudo.connector] Subscribed to MQTT broker with topic: valetudo/Robi` but there is no connection closure `_LOGGER.debug(self._mqtt_topic + ": Stopped and disconnected from MQTT broker.")` before, as when I disable the configured camera and re-enable it.

**Comment by sca075** [comment]
@NODeeJay thanks for the report, do you use the MQTT_add on of Home Assistant or MQTT is on another machine? If during the setup of the camera you configured the Broker Hostname this should be because on your config there must be  external MQTT, by default the camera point to the HA Broker ADD on.  It would be appreciated the the full log you got to better understand what is going on. We did confirm that the Json is correctly grabbed and as per you are in HA OS I guess you run under docker and you use the HA Broker Addon, it that correct?

**Comment by NODeeJay** [comment]
> @NODeeJay thanks for the report, do you use the MQTT_add on of Home Assistant or MQTT is on another machine?

I configured core-mosquitto, I use the internal standard MQTT, no fancy new version or external broker running somewhere.
![image](https://github.com/sca075/valetudo_vacuum_camera/assets/83764033/92466e33-48c5-4c15-8512-d17082ef28bc)

I played a bit further around, using the connection with SSL core-mosquitto:8883 or the hostname I use from the robot, with or without port and SSL. It seems that the port is not processed at all but I did not check it in the code. Also with SSL it seems not to connect at all to the broker. The FQDN or core-mosquitto as host did not make any difference, I see the client connection in the MQTT broker log, which corresponds to the log entry from the component.

I am still wondering why there are so many reconnects in a short time?
```
2023-08-26 14:10:55.366 DEBUG (Thread-1538 (_thread_main)) [custom_components.valetudo_vacuum_camera.valetudo.connector] Subscribed to MQTT broker with topic: valetudo/Robi
2023-08-26 14:10:56.370 DEBUG (Thread-1538 (_thread_main)) [custom_components.valetudo_vacuum_camera.valetudo.connector] Subscribed to MQTT broker with topic: valetudo/Robi
2023-08-26 14:10:58.375 DEBUG (Thread-1538 (_thread_main)) [custom_components.valetudo_vacuum_camera.valetudo.connector] Subscribed to MQTT broker with topic: valetudo/Robi
2023-08-26 14:11:00.638 WARNING (MainThread) [homeassistant.components.sensor] Updating snmp sensor took longer than the scheduled update interval 0:00:05
2023-08-26 14:11:00.648 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.hplj2055dn_printer_status_code is taking over 10 seconds
2023-08-26 14:11:00.653 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.hplj2055dn_printer_error_code is taking over 10 seconds
2023-08-26 14:11:02.379 DEBUG (Thread-1538 (_thread_main)) [custom_components.valetudo_vacuum_camera.valetudo.connector] Subscribed to MQTT broker with topic: valetudo/Robi
2023-08-26 14:11:05.638 WARNING (MainThread) [homeassistant.components.sensor] Updating snmp sensor took longer than the scheduled update interval 0:00:05
2023-08-26 14:11:10.383 DEBUG (Thread-1538 (_thread_main)) [custom_components.valetudo_vacuum_camera.valetudo.connector] Subscribed to MQTT broker with topic: valetudo/Robi
```

Which full log do you mean?

No worries, you started a great piece of work and am very happy to try it and get it running. Thank you for your support!

**Comment by sca075** [comment]
Probably I know what is the issue.. the user name and password you need to use are the same one you use to connect the vacuum to MQTT. the user name homeassistant is reserved to home assistant so the client can't connect your MQTT broker for this reason:
- go on Settings / Add Ons / MosquitoBroker / Configuration..
- check the user name and password that you use there to connect your devices to MQTT, and please use those credential for the camera. 

Just let me if this is the way you already use or what is the result after using those credentials. If I'm correct you followed to the letter the instructions, this would means I will need to update the documentation instead of the integration :) 
Thanks once again for time, regards.

**Comment by NODeeJay** [comment]
Right you are that is the issue. I used the same credentials as for the robi and it worked immediately. Strange, that I have other addons and integrations that connect fine with the homeassistant user.

**Comment by NODeeJay** [comment]
Right you are that is the issue. I used the same credentials as for the robi and it worked immediately. Strange, that I have other addons and integrations that connect fine with the homeassistant user.

Thank you for your help, the card is map is streaming fine into Piotrs card :-)

**Comment by NODeeJay** [comment]
Right you are that is the issue. I used the same credentials as for the robi and it worked immediately. Strange, that I have other addons and integrations that connect fine with the homeassistant user.

Thank you for your help, the card is streaming fine into Piotrs card :-)

**Comment by sca075** [comment]
It is currently a work in progress soon it will be not required thanks to @rohankapoorcom
