### ISSUE TITLE
Mapper connects the different paths of a Dreame Z10

### ISSUE THREAD

**Issue by tobi1449** [sca075/valetudo_vacuum_camera#39]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

When creating the image from my Dreame Z10, the mapper connects all different paths present in the mapping data. (I.e. it draws a line from the last point of the first path to the first point of the second path and so on). 
These paths are supposed to be drawn independently, otherwise it results in some weird zig zack lines all across the map.

### What version of an integration has described problem?

1.4.4

### What vacuum model do you have problems with?

Dreame Z10

### Please firmware installed on your Vacuum.

2023.03.0

### What version of Home Assistant do you use?

2023.10.1

### What type of installation are you running?

Home Assistant Supervised

**Comment by sca075** [comment]
@tobi1449 I will check the data and get back to you as soon

**Comment by sca075** [comment]
@tobi1449 problem found, next release will fix it ;) thanks for the report.

**Comment by sca075** [comment]
@tobi1449 fix released with v1.4.5 please confirm if we can close this issue ;)

**Comment by tobi1449** [comment]
Looks good, thanks.
