### ISSUE TITLE
Unknown Error at color change

### ISSUE THREAD

**Issue by Raabi91** [sca075/valetudo_vacuum_camera#55]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

when i change the colors and press save an error message appears

![Screenshot 2023-12-16 225207](https://github.com/sca075/valetudo_vacuum_camera/assets/38133278/3acda209-0f81-4792-8f49-3af77f446ca7)

### What version of an integration has described problem?

1.5.1

### What vacuum model do you have problems with?

Dreame D9

### Please firmware installed on your Vacuum.

2023.10.0

### What version of Home Assistant do you use?

2023.12.3

### What type of installation are you running?

Home Assistant OS

**Comment by sca075** [comment]
I just completed a test on my side and I couldn't reproduce the phenomena you reported. But will soon release a new version of the camera.. can you please share the logs from Home Assistant? Is it happening only with the base colours? Version 1.5.2 is scheduled to be release tomorrow morning, CET 12:00PM.

**Comment by sca075** [comment]
@Raabi91 I just pushed the code (there is some check to do before releasing) in any cases if you download it from main (by selecting it from HACS) it should give you an hint if the issue still there or not. Would be appreciated your kind feedback as per this would allow me to eventually do the required corrections..

**Comment by Raabi91** [comment]
> @Raabi91 I just pushed the code (there is some check to do before releasing) in any cases if you download it from main (by selecting it from HACS) it should give you an hint if the issue still there or not. Would be appreciated your kind feedback as per this would allow me to eventually do the required corrections..

download 1.5.2 from github uploaded it to ha, restart homeassistant and now its working

**Comment by sca075** [comment]
@Raabi91 thanks a lot for confirming :)
