### ISSUE TITLE
GC logging causing extreme performance hit for HA

### ISSUE THREAD

**Issue by droans** [sca075/valetudo_vacuum_camera#76]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

https://github.com/sca075/valetudo_vacuum_camera/blame/959eb5aa126a05808330b4cae555caf98f8fa0c9/custom_components/valetudo_vacuum_camera/camera.py#L277

The debug line set above is causing all gc events in HA to be logged. Unfortunately this is causing an extremely massive slowdown.  I'm running on a server with Ryzen 5600x and 32GB of RAM and simply turning a light on takes 5-10 seconds. Loading HA can take 2-3 minutes.

Pulling the Docker logs will show that it is logging anywhere from 5-500+ times per second. 

### What version of an integration has described problem?

v1.5.7.2

### What vacuum model do you have problems with?

N/A

### Please firmware installed on your Vacuum.

N/A

### What version of Home Assistant do you use?

2024.1.6

### What type of installation are you running?

Home Assistant Container

### Logs or Errors shown in the HA snapshots (please enable the Debug Mode)

```shell
gc: collecting generation 1...
gc: objects in each generation: 879 7690 1407440
gc: objects in permanent generation: 0
gc: done, 0 unreachable, 0 uncollectable, 0.0001s elapsed
```

**Comment by droans** [comment]
It might be happening there, too. The messages weren't showing up in the HA logs, only when I ran a docker logs command. 

If you have the Portainer add-on with HAOS, you can try pulling the logs there and seeing if you can find it. 

I suppose the architecture for HAOS could also be preventing it.

**Comment by sca075** [comment]
Portainer?? I will check it out thanks for the advice ;)

**Comment by sca075** [comment]
@droans v1.5.7.3 ready thanks a lot please close the issue if all is getting okay, I will use the add-on you advised to monitor the camera in the future, thanks a lot once again

**Comment by droans** [comment]
Seems to have done it! Thanks!
