### ISSUE TITLE
Problem rendering Japanese/Chinese characters in status text.

### ISSUE THREAD

**Issue by kodbuzz** [sca075/valetudo_vacuum_camera#86]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Japanese and Chinese characters are displayed incorrectly when the room is named in these languages.

![image](https://github.com/sca075/valetudo_vacuum_camera/assets/77547202/f3a7d499-a9c2-4f6c-9754-277b9f8aa7f6)

I attempted to resolve the issue using 'Pillow' with the specified Noto-CJK font from 'https://github.com/notofonts/noto-cjk/'. While this approach worked, it resulted in the loss of the charging indicator letter (lightning). Additionally, adding an extra font file, which is approximately 60MB, it does present another challenge imho.

Is there any other approach that could effectively address this issue?

![image](https://github.com/sca075/valetudo_vacuum_camera/assets/77547202/f5ae37cc-2a9e-4b78-afa8-ae3d05e0a069)
This image shows the results using 'Pillow' with font Noto-CJK.

### What version of an integration has described problem?

1.5.8

### What vacuum model do you have problems with?

Mi Robot Vacuum-Mop P (Viomi v7)

### Please firmware installed on your Vacuum.

0047 - Valetudo 2023.12.0

### What type of platform you use?

VEMLinux (Virtual Machine) such as Proxmox, VMWare, etc.

### What version of Home Assistant do you use?

2024.2.4

### What type of installation are you running?

Home Assistant OS

**Comment by sca075** [comment]
@kodbuzz thanks as usual, I will try to fix it, as it is a limitation with the characters (I did change the fonts today) would you please double check downloading the Main please?

**Comment by kodbuzz** [comment]
> @kodbuzz thanks as usual, I will try to fix it, as it is a limitation with the characters (I did change the fonts today) would you please double check downloading the Main please?

@sca075 Good evening, since I'm on the latest commit, which was made approx 5hrs ago, it seems that the issue still persists. Btw I'm not certain if Cyrillic alphabets encounter the same rendering issue, shall we test with Cyrillic as well?

**Comment by kodbuzz** [comment]
@sca075 unfortunately no, afaik the "status_text" field has never rendered correctly when it contains Japanese/Chinese characters even in previous versions, It seems like more of an aesthetic issue to me, so I didn't submit the problem in the past few weeks as I was quite occupied too.

**Comment by sca075** [comment]
@kodbuzz okay we will found a way to make it work 😉

**Comment by sca075** [comment]
@kodbuzz release 1.5.9-rc1 include a font that can show the Japanese characters
![Screenshot 2024-02-28 at 22 45 05](https://github.com/sca075/valetudo_vacuum_camera/assets/82227818/f978d37b-89f4-4e5f-8fd7-772bc2743401)
If you confirm it I will use this font as soon I release the 1.5.9 ;)

**Comment by kodbuzz** [comment]
@sca075 confirmed, it works like a charm, thank you!

**Comment by sca075** [comment]
> @sca075 confirmed, it works like a charm, thank you!
@kodbuzz I tested it and it looks Hiragana, Katakana is probably okay but Kanji as well Cyrillic on the status text could be a little challenging but not impossible.. for the time be if we are okay with it will use this font later on probably I can try to implement a menu were to select the language (font) to use for the status test.. will close the issue but open a discussion as usual to keep trace of this idea, thanks again.
